// tests/sync-status.test.mjs
// Tests for scripts/sync-status.mjs logic

import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';

// Inline the counting + block logic to test it independently
function buildAutoBlock(count, date) {
  return `<!-- AUTO-GENERATED by scripts/sync-status.mjs — do not edit this block manually -->
<!-- last-updated: ${date} -->
**当前笔记数：${count} 篇**（自动统计，每次推 main 更新）
<!-- END AUTO-GENERATED -->`;
}

function insertOrReplaceBlock(content, count, date) {
  const autoBlock = buildAutoBlock(count, date);
  const blockRe = /<!-- AUTO-GENERATED[\s\S]*?END AUTO-GENERATED -->/;
  if (blockRe.test(content)) {
    return content.replace(blockRe, autoBlock);
  }
  // Insert at top
  return autoBlock + '\n\n' + content;
}

await test('builds auto block with correct count', () => {
  const block = buildAutoBlock(796, '2026-01-01');
  assert.ok(block.includes('796 篇'), 'block should contain count');
  assert.ok(block.includes('last-updated: 2026-01-01'), 'block should contain date');
});

await test('inserts block into file without one', () => {
  const content = '# STATUS\n\nSome content';
  const updated = insertOrReplaceBlock(content, 100, '2026-01-01');
  assert.ok(updated.includes('100 篇'), 'updated content should contain count');
  assert.ok(updated.includes('# STATUS'), 'original content should be preserved');
});

await test('replaces existing block in file', () => {
  const existing = buildAutoBlock(50, '2025-01-01');
  const content = existing + '\n\n# STATUS\n\nSome content';
  const updated = insertOrReplaceBlock(content, 796, '2026-01-01');
  assert.ok(updated.includes('796 篇'), 'should show new count');
  assert.ok(!updated.includes('50 篇'), 'should not show old count');
});

await test('sync-status --check passes when counts match', () => {
  // Test the check logic inline
  function checkCount(content, expected) {
    const match = content.match(/当前笔记数：(\d+) 篇/);
    if (!match || parseInt(match[1]) !== expected) {
      return { ok: false, actual: match ? parseInt(match[1]) : null };
    }
    return { ok: true };
  }

  const contentWithBlock = `<!-- AUTO-GENERATED by scripts/sync-status.mjs — do not edit this block manually -->
<!-- last-updated: 2026-01-01 -->
**当前笔记数：796 篇**（自动统计，每次推 main 更新）
<!-- END AUTO-GENERATED -->

# STATUS`;

  assert.deepEqual(checkCount(contentWithBlock, 796), { ok: true });
  assert.deepEqual(checkCount(contentWithBlock, 100), { ok: false, actual: 796 });
  assert.deepEqual(checkCount('# No block', 100), { ok: false, actual: null });
});
