#!/usr/bin/env node
// 同步 STATUS-PAPERS.md / STATUS-PROJECTS.md 顶部「自动生成」统计块
// 用法：
//   node scripts/sync-status.mjs          # 写入 STATUS 文件
//   node scripts/sync-status.mjs --check  # 仅校验（不写入），不一致则退出码 1

import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const CHECK_ONLY = process.argv.includes('--check');

async function countMd(dir) {
  try {
    const entries = await fs.readdir(dir);
    return entries.filter(f => f.endsWith('.md') && !f.startsWith('_')).length;
  } catch {
    return 0;
  }
}

function todayIso() {
  return new Date().toISOString().slice(0, 10);
}

function buildAutoBlock(kind, count, date) {
  return `<!-- AUTO-GENERATED by scripts/sync-status.mjs — do not edit this block manually -->
<!-- last-updated: ${date} -->
**当前笔记数：${count} 篇**（自动统计，每次推 main 更新）
<!-- END AUTO-GENERATED -->`;
}

async function syncFile(filePath, kind, count) {
  let content;
  try {
    content = await fs.readFile(filePath, 'utf8');
  } catch {
    console.warn(`sync-status: ${filePath} not found, skipping`);
    return { changed: false };
  }

  const autoBlock = buildAutoBlock(kind, count, todayIso());
  const blockRe = /<!-- AUTO-GENERATED[\s\S]*?END AUTO-GENERATED -->/;

  let newContent;
  if (blockRe.test(content)) {
    newContent = content.replace(blockRe, autoBlock);
  } else {
    // Insert after first --- frontmatter block, or at very top
    const firstH1 = content.indexOf('\n# ');
    if (firstH1 !== -1) {
      newContent = content.slice(0, firstH1 + 1) + autoBlock + '\n' + content.slice(firstH1 + 1);
    } else {
      newContent = autoBlock + '\n\n' + content;
    }
  }

  const changed = newContent !== content;

  if (CHECK_ONLY) {
    // In check mode: verify the block exists and count matches
    const match = content.match(/当前笔记数：(\d+) 篇/);
    if (!match || parseInt(match[1]) !== count) {
      console.error(`sync-status --check FAIL: ${path.basename(filePath)} shows ${match ? match[1] : '(no block)'} but disk has ${count}`);
      return { changed: true };
    }
    return { changed: false };
  }

  if (changed) {
    await fs.writeFile(filePath, newContent);
    console.log(`sync-status: updated ${path.basename(filePath)} (${count} 篇)`);
  } else {
    console.log(`sync-status: ${path.basename(filePath)} already up-to-date (${count} 篇)`);
  }
  return { changed };
}

async function main() {
  const papersCount = await countMd(path.join(ROOT, 'src/content/docs/papers'));
  const projectsCount = await countMd(path.join(ROOT, 'src/content/docs/projects'));

  const results = await Promise.all([
    syncFile(path.join(ROOT, 'STATUS-PAPERS.md'), 'papers', papersCount),
    syncFile(path.join(ROOT, 'STATUS-PROJECTS.md'), 'projects', projectsCount),
  ]);

  if (CHECK_ONLY) {
    const anyFailed = results.some(r => r.changed);
    if (anyFailed) {
      console.error('sync-status --check: STATUS files are out of sync with disk counts');
      process.exit(1);
    } else {
      console.log('sync-status --check: OK');
    }
  }
}

main().catch(err => {
  console.error('sync-status error:', err);
  process.exit(1);
});
